// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFlcRUmuCmmqf0xQDzh3U3_V4LRRD3p0Q',
    appId: '1:949793563085:web:d646a3a0b241c820c62484',
    messagingSenderId: '949793563085',
    projectId: 'mawakay-3b1ac',
    authDomain: 'mawakay-3b1ac.firebaseapp.com',
    databaseURL: 'https://mawakay-3b1ac-default-rtdb.firebaseio.com',
    storageBucket: 'mawakay-3b1ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsCdww6o1fKA7O_cmsglRsdSvfxFZ1Or8',
    appId: '1:949793563085:android:0c8139dabd6808ddc62484',
    messagingSenderId: '949793563085',
    projectId: 'mawakay-3b1ac',
    databaseURL: 'https://mawakay-3b1ac-default-rtdb.firebaseio.com',
    storageBucket: 'mawakay-3b1ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbvmw_EG3j26RpFb9IPjVMXS634uiYvM',
    appId: '1:949793563085:ios:184e4f3f9c52d88cc62484',
    messagingSenderId: '949793563085',
    projectId: 'mawakay-3b1ac',
    databaseURL: 'https://mawakay-3b1ac-default-rtdb.firebaseio.com',
    storageBucket: 'mawakay-3b1ac.appspot.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbvmw_EG3j26RpFb9IPjVMXS634uiYvM',
    appId: '1:949793563085:ios:184e4f3f9c52d88cc62484',
    messagingSenderId: '949793563085',
    projectId: 'mawakay-3b1ac',
    databaseURL: 'https://mawakay-3b1ac-default-rtdb.firebaseio.com',
    storageBucket: 'mawakay-3b1ac.appspot.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFlcRUmuCmmqf0xQDzh3U3_V4LRRD3p0Q',
    appId: '1:949793563085:web:4563cb3696fbdafec62484',
    messagingSenderId: '949793563085',
    projectId: 'mawakay-3b1ac',
    authDomain: 'mawakay-3b1ac.firebaseapp.com',
    databaseURL: 'https://mawakay-3b1ac-default-rtdb.firebaseio.com',
    storageBucket: 'mawakay-3b1ac.appspot.com',
  );
}
